# Generated by Django 4.2.11 on 2024-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0002_auto_20240317_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='civil_status',
            field=models.CharField(choices=[('M.', 'M.'), ('Mme.', 'Mme.')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
