# Generated by Django 4.2.11 on 2024-03-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='entre',
            field=models.CharField(choices=[('ELEC', 'Electricity'), ('GAZ', 'Gas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='compteur',
            name='pdl',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
